#!/bin/bash

echo "----------------------------------------" > L_SenseMe.lua
echo "-- Globals" >> L_SenseMe.lua
echo "----------------------------------------" >> L_SenseMe.lua
echo "" >> L_SenseMe.lua
cat L_SenseMe/globals.lua >> L_SenseMe.lua
echo "" >> L_SenseMe.lua

echo "----------------------------------------" >> L_SenseMe.lua
echo "-- Vera" >> L_SenseMe.lua
echo "----------------------------------------" >> L_SenseMe.lua
echo "" >> L_SenseMe.lua
cat L_SenseMe/vera.lua >> L_SenseMe.lua
echo "" >> L_SenseMe.lua

echo "----------------------------------------" >> L_SenseMe.lua
echo "-- Plugin" >> L_SenseMe.lua
echo "----------------------------------------" >> L_SenseMe.lua
echo "" >> L_SenseMe.lua
cat L_SenseMe/plugin.lua >> L_SenseMe.lua
echo "" >> L_SenseMe.lua

echo "----------------------------------------" >> L_SenseMe.lua
echo "-- Debug" >> L_SenseMe.lua
echo "----------------------------------------" >> L_SenseMe.lua
echo "" >> L_SenseMe.lua
cat L_SenseMe/debug.lua >> L_SenseMe.lua
echo "" >> L_SenseMe.lua

echo "----------------------------------------" >> L_SenseMe.lua
echo "-- Task" >> L_SenseMe.lua
echo "----------------------------------------" >> L_SenseMe.lua
echo "" >> L_SenseMe.lua
cat L_SenseMe/task.lua >> L_SenseMe.lua
echo "" >> L_SenseMe.lua

echo "----------------------------------------" >> L_SenseMe.lua
echo "-- Utilities" >> L_SenseMe.lua
echo "----------------------------------------" >> L_SenseMe.lua
echo "" >> L_SenseMe.lua
cat L_SenseMe/utilities.lua >> L_SenseMe.lua
echo "" >> L_SenseMe.lua

echo "----------------------------------------" >> L_SenseMe.lua
echo "-- Settings" >> L_SenseMe.lua
echo "----------------------------------------" >> L_SenseMe.lua
echo "" >> L_SenseMe.lua
cat L_SenseMe/settings.lua >> L_SenseMe.lua
echo "" >> L_SenseMe.lua

echo "----------------------------------------" >> L_SenseMe.lua
echo "-- Startup" >> L_SenseMe.lua
echo "----------------------------------------" >> L_SenseMe.lua
echo "" >> L_SenseMe.lua
cat L_SenseMe/startup.lua >> L_SenseMe.lua
echo "" >> L_SenseMe.lua
